kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |-
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    containerLogMaxSize: 500Mi
  - |-
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    controllerManager:
      extraArgs:
        node-monitor-grace-period: "7200s"
        node-monitor-period: "3600s"
        kube-api-qps: "1000"
        kube-api-burst: "1000"
        concurrent-job-syncs: "100"
    etcd:
      local:
        extraArgs:
          quota-backend-bytes: "8589934592"
          auto-compaction-mode: revision
          auto-compaction-retention: "1000"
    apiServer:
      extraArgs:
        max-mutating-requests-inflight: "20000"
        max-requests-inflight: "20000"
        audit-policy-file: /etc/kubernetes/policies/audit-policy.yaml
        audit-log-path: /var/log/kubernetes/kube-apiserver-audit.log
        audit-log-maxsize: "10240"
        audit-log-maxage: "7"
        audit-log-maxbackup: "3"
      extraVolumes:
      - name: audit-policies
        hostPath: /etc/kubernetes/policies
        mountPath: /etc/kubernetes/policies
        readOnly: true
        pathType: DirectoryOrCreate
      - name: audit-logs
        hostPath: /var/log/kubernetes
        mountPath: /var/log/kubernetes
        readOnly: false
        pathType: DirectoryOrCreate
    scheduler:
      extraArgs:
        kube-api-qps: "1000"
        kube-api-burst: "1000"
  extraMounts:
  - hostPath: ./manifests/audit-policy.yaml
    containerPath: /etc/kubernetes/policies/audit-policy.yaml
    readOnly: true
  - hostPath: ./logs
    containerPath: /var/log/kubernetes
    readOnly: false
  extraPortMappings:
  - containerPort: 30003
    hostPort: 31003
    protocol: TCP
  - containerPort: 30004
    hostPort: 31004
    protocol: TCP
